apiVersion: v1
kind: Secret
metadata:
  name: apm-secrets
  namespace: monitoring
type: Opaque
stringData:
  datadog-api-key: "placeholder-datadog-key"
  newrelic-api-key: "5D2BFBCE56FBCBD3C894798782E2046D7E7DD1D3ADE062989B49C299DCE53299"
