apiVersion: v1
kind: Secret
metadata:
  name: apm-secrets
  namespace: monitoring
type: Opaque
stringData:
  datadog-api-key: "placeholder-datadog-key"
  newrelic-api-key: "A0E9ACBFB533DC16546863D504F5A2EE7EB6D3F6720E2AFDE48FE6C28AA6A819"
