apiVersion: v1
kind: Secret
metadata:
  name: apm-secrets
  namespace: monitoring
type: Opaque
stringData:
  datadog-api-key: "placeholder-replace-in-github-secrets-or-kubectl"
  newrelic-api-key: "placeholder-replace-in-github-secrets-or-kubectl"
