apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: togglemaster
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: VG9nZ2xlbWFzdGVyMTIz
  MASTER_KEY: R0Q5LzV4dDluK0h1WXU3c0hVbm40S2RqUVptekRNakRneWVmL2RubXZTbz0=
