apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: togglemaster
data:
  AUTH_DB_HOST: "togglemaster-homolog-auth-db.clrqrtilufsf.us-east-1.rds.amazonaws.com"
  FLAG_DB_HOST: "togglemaster-homolog-flag-db.clrqrtilufsf.us-east-1.rds.amazonaws.com"
  TARGETING_DB_HOST: "togglemaster-homolog-targeting-db.clrqrtilufsf.us-east-1.rds.amazonaws.com"

  REDIS_HOST: "togglemaster-homolog-redis.ln1equ.0001.use1.cache.amazonaws.com:6379"
  REDIS_TLS: "false"
  REDIS_URL: "redis://togglemaster-homolog-redis.ln1equ.0001.use1.cache.amazonaws.com:6379"

  AUTH_SERVICE_URL: "http://auth-service:8001"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  EVALUATION_SERVICE_URL: "http://evaluation-service:8004"
  ANALYTICS_SERVICE_URL: "http://analytics-service:8005"

  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/781659100115/togglemaster-analytics-queue"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector.monitoring.svc.cluster.local:4317"
  
  AWS_SQS_ENDPOINT_URL: ""
  AWS_DYNAMODB_ENDPOINT_URL: ""
  
  AUTH_DATABASE_URL: "postgres://postgres:Togglemaster123@togglemaster-homolog-auth-db.clrqrtilufsf.us-east-1.rds.amazonaws.com:5432/togglemaster_homolog_auth"
  FLAG_DATABASE_URL: "postgres://postgres:Togglemaster123@togglemaster-homolog-flag-db.clrqrtilufsf.us-east-1.rds.amazonaws.com:5432/togglemaster_homolog_flag"
  TARGETING_DATABASE_URL: "postgres://postgres:Togglemaster123@togglemaster-homolog-targeting-db.clrqrtilufsf.us-east-1.rds.amazonaws.com:5432/togglemaster_homolog_targeting"
