apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: togglemaster
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: VG9nZ2xlbWFzdGVyIzEyMzQ=
  MASTER_KEY: R0Q5LzV4dDluK0h1WXU3c0hVbm40S2RqUVptekRNakRneWVmL2RubXZTbz0=

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: togglemaster
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""
