name: Analytics Service CI

on:
  push:
    branches: [main]
    paths:
      - "backend-services/analytics-service/**"
      - ".github/workflows/analytics-service-ci.yml"
      - ".github/workflows/service-ci-base.yml"

jobs:
  analytics_service_ci:
    permissions:
      contents: write
    uses: ./.github/workflows/service-ci-base.yml
    with:
      service_name: analytics-service
      service_path: backend-services/analytics-service
      language: python
      image_name: analytics-service
      trivy_fail_on_critical: true
    secrets: inherit
