name: Auth Service CI

on:
  push:
    branches: [main, Fase3, Fase4]
    paths:
      - "backend-services/auth-service/**"
      - ".github/workflows/auth-service-ci.yml"
      - ".github/workflows/service-ci-base.yml"
  workflow_dispatch:

jobs:
  auth_service_ci:
    uses: ./.github/workflows/service-ci-base.yml
    with:
      service_name: auth-service
      service_path: backend-services/auth-service
      language: go
      image_name: auth-service
      trivy_fail_on_critical: true
    secrets: inherit
