name: Evaluation Service CI

on:
  push:
    branches: [main]
    paths:
      - "backend-services/evaluation-service/**"
      - ".github/workflows/evaluation-service-ci.yml"
      - ".github/workflows/service-ci-base.yml"

jobs:
  evaluation_service_ci:
    permissions:
      contents: write
    uses: ./.github/workflows/service-ci-base.yml
    with:
      service_name: evaluation-service
      service_path: backend-services/evaluation-service
      language: go
      image_name: evaluation-service
      trivy_fail_on_critical: true
    secrets: inherit
