name: Flag Service CI

on:
  push:
    branches: [main]
    paths:
      - "backend-services/flag-service/**"
      - ".github/workflows/flag-service-ci.yml"
      - ".github/workflows/service-ci-base.yml"

jobs:
  flag_service_ci:
    permissions:
      contents: write
    uses: ./.github/workflows/service-ci-base.yml
    with:
      service_name: flag-service
      service_path: backend-services/flag-service
      language: python
      image_name: flag-service
      trivy_fail_on_critical: true
    secrets: inherit
