name: Targeting Service CI

on:
  push:
    branches: [main, Fase3, Fase4]
    paths:
      - "backend-services/targeting-service/**"
      - ".github/workflows/targeting-service-ci.yml"
      - ".github/workflows/service-ci-base.yml"
  workflow_dispatch:

jobs:
  targeting_service_ci:
    uses: ./.github/workflows/service-ci-base.yml
    with:
      service_name: targeting-service
      service_path: backend-services/targeting-service
      language: python
      image_name: targeting-service
      trivy_fail_on_critical: true
    secrets: inherit
